Hometask 7
Pxsha/workshop pull request #7
Opened 2019-12-16 15:13 UTC by Pxsha

2019-12-19 21:08 UTC, illarionovEA requested changes
задание не выполнено

2019-12-20 11:37 UTC, Pxsha commented
разрешите, пожалуйста, уточнить, что именно мне нужно доделать?

2019-12-20 12:47 UTC, illarionovEA commented
Вывести 10 самых вероятных слов по каждой теме, интерпретировать темы и соотнести с темами из датасета

2019-12-22 01:13 UTC, Pxsha commented
Исправил ошибки. Теперь темы интерпретируются лучше. Ссылка на codewars: https://www.codewars.com/users/Pxsha

2019-12-22 16:00 UTC, illarionovEA approved these changes

2019-12-22 18:38 UTC, merged